services:
  accounts:
    image: "r.edu.codespring.ro/training-assets/kubernetes-fozocskek/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  cards:
    image: "r.edu.codespring.ro/training-assets/kubernetes-fozocskek/cards:v1"
    container_name: cards-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  loans:
    image: "r.edu.codespring.ro/training-assets/kubernetes-fozocskek/loans:v1"
    container_name: loans-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank

networks:
  easybank:
    driver: "bridge"