deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: r.edu.codespring.ro/training-assets/kubernetes-fozocskek/gatewayserver
  tag: v6

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: true
otel_enabled: false
kafka_enabled: false
datasource: false

secretName: registry-credential