deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: r.edu.codespring.ro/training-assets/kubernetes-fozocskek/eurekaserver
  tag: v6

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resourceserver_enabled: false
otel_enabled: false
kafka_enabled: false
datasource: false
serviceType: true

secretName: registry-credential