apiVersion: v1
kind: ConfigMap
metadata:
  name: easybank-configmap
data:
    SPRING_PROFILES_ACTIVE: default
    SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: root
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
    CONFIGSERVER_APPLICATION_NAME: configserver
    EUREKA_APPLICATION_NAME: eurekaserver
    ACCOUNTS_APPLICATION_NAME: accounts
    ACCOUNTS_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/mysql
    CARDS_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/mysql
    LOANS_DATASOURCE_URL: jdbc:mysql://loansdb:3306/mysql
    LOANS_APPLICATION_NAME: loans
    CARDS_APPLICATION_NAME: cards
    GATEWAY_APPLICATION_NAME: gatewayserver
    KEYCLOAK_ADMIN: admin
    KEYCLOAC_ADMIN_PASSWORD: admin
    SPRING_SECUTIRY_OAUTH2_RESOURCESERVER_JWT_JWT-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
    