deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: r.edu.codespring.ro/training-assets/kubernetes-fozocskek/message
  tag: v7

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resourceserver_enabled: false
otel_enabled: false
kafka_enabled: true
datasource: false

secretName: registry-credential